spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/heatews
    username: heat
    password: heat_dev
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,flyway
  endpoint:
    health:
      show-details: always

server:
  port: 8080
